# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07563103dcdf574f20c559d4ec4f9cd5a984d0d2346778d96cfb49f9bb1ad477ef865e87df77491e418d423d55f29bf7002bc10f29a00cdc95f520ee592d7167

test:
  secret_key_base: 743bfe5087e78678f5f3da95c3b582e64f3a9ecca6437e745f8a0acc69fb118bd17efefb18c1d5db833f0ec6b75765586bc3e04299dc62d28580d1b4047defed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
